import { BaseAgent, AgentInput, AgentOutput } from "../../agents";
import { prisma } from "@/lib/prisma";
import { getAuthenticatedClient, getCalendarClient } from "@/services/google";

export class CalendarAgent implements BaseAgent {
  name = "Calendar Execution Agent";

  async execute(input: AgentInput): Promise<AgentOutput> {
    const logs: string[] = ["Starting Calendar Execution Agent..."];
    try {
      const candidates = await prisma.candidate.findMany({
        where: {
          workflowId: input.workflowId as string,
          status: "SHORTLISTED",
        },
      });

      if (candidates.length === 0) {
        logs.push("No shortlisted candidates found to schedule. Skipping.");
        return { success: true, logs, outputData: { actionCount: 0 } };
      }

      logs.push(`Generating calendar meeting placeholders for ${candidates.length} candidates...`);

      // Set default meeting time: tomorrow at 10 AM, increments by 1 hour per candidate.
      // If prompt states a date keyword (like "23rd", "23 of this month", or a day index), parse it dynamically.
      let baseDate = new Date();
      
      const promptLower = input.prompt.toLowerCase();
      
      // Look for format: "24 july 2026", "24 july", or "july 24"
      const months = ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"];
      const monthsShort = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
      
      let parsedDate: Date | null = null;
      
      // Match "24 july 2026" or "24th july 2026" or "24 jul 2026"
      const matchFullDate = promptLower.match(/(\d{1,2})(?:th|rd|st|nd)?\s+(january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|oct|nov|dec)\s*(\d{4})?/);
      
      if (matchFullDate) {
        const day = parseInt(matchFullDate[1], 10);
        const monthName = matchFullDate[2];
        const year = matchFullDate[3] ? parseInt(matchFullDate[3], 10) : baseDate.getFullYear();
        
        let monthIdx = months.indexOf(monthName);
        if (monthIdx === -1) {
          monthIdx = monthsShort.indexOf(monthName);
        }
        
        if (monthIdx !== -1) {
          parsedDate = new Date(year, monthIdx, day, 10, 0, 0, 0);
        }
      }
      
      if (!parsedDate) {
        // Fallback to match relative/numeric days: "on the 23rd", "23 of this month"
        const matchMonthDay = promptLower.match(/(?:on the\s+|on\s+|date\s+)(\d{1,2})/);
        const matchDirectDay = promptLower.match(/(\d{1,2})(?:th|rd|st|nd)?\s+(?:of\s+)?(?:this\s+)?month/);
        
        let targetDay = baseDate.getDate() + 1; // Default: tomorrow
        if (matchMonthDay) {
          targetDay = parseInt(matchMonthDay[1], 10);
        } else if (matchDirectDay) {
          targetDay = parseInt(matchDirectDay[1], 10);
        }
        
        baseDate.setDate(targetDay);
        baseDate.setHours(10, 0, 0, 0);
      } else {
        baseDate = parsedDate;
      }

      for (const cand of candidates) {
        const dateString = baseDate.toISOString();
        const email = cand.email || "placeholder@example.com";

        logs.push(`Planning meeting for ${cand.name} at ${dateString}`);

        await prisma.meetingHistory.create({
          data: {
            userId: input.userId,
            candidateName: cand.name,
            candidateEmail: email,
            subject: `Interview invitation: ${cand.name} / AgentOS HR`,
            body: `AgentOS HR Autogenerated Interview Session for candidate ${cand.name}.\nRequirements review session.`,
            date: dateString,
            status: "PENDING_APPROVAL",
          },
        });

        // Increment time for next candidate
        baseDate.setHours(baseDate.getHours() + 1);
        logs.push(`Created pending meeting Action for ${cand.name}`);
      }

      return { success: true, logs, outputData: { status: "AWAITING_APPROVAL" } };
    } catch (e: any) {
      logs.push(`Calendar Execution Agent failed: ${e.message}`);
      return { success: false, logs, outputData: null, error: e.message };
    }
  }

  static async createMeeting(actionId: string, googleTokenJson: string): Promise<{ success: boolean; meetingLink?: string; error?: string }> {
    try {
      const action = await prisma.meetingHistory.findUnique({ where: { id: actionId } });
      if (!action) throw new Error("Action not found.");

      const auth = getAuthenticatedClient(googleTokenJson);
      const calendar = getCalendarClient(auth);

      const start = new Date(action.date || new Date());
      const end = new Date(start.getTime() + 45 * 60 * 1000);

      const event = {
        summary: action.subject || "Interview with AgentOS HR",
        description: action.body || "",
        start: {
          dateTime: start.toISOString(),
          timeZone: "UTC",
        },
        end: {
          dateTime: end.toISOString(),
          timeZone: "UTC",
        },
        attendees: [{ email: action.candidateEmail }],
        conferenceData: {
          createRequest: {
            requestId: `agentos-${action.id}`,
            conferenceSolutionKey: {
              type: "hangoutsMeet",
            },
          },
        },
      };

      const response = await calendar.events.insert({
        calendarId: "primary",
        requestBody: event,
        conferenceDataVersion: 1,
      });

      const meetingLink = response.data.hangoutLink || response.data.htmlLink || "";

      await prisma.meetingHistory.update({
        where: { id: actionId },
        data: {
          status: "SCHEDULED",
          meetingLink,
        },
      });

      return { success: true, meetingLink };
    } catch (e: any) {
      await prisma.meetingHistory.update({
        where: { id: actionId },
        data: { status: "FAILED" },
      });
      return { success: false, error: e.message };
    }
  }
}
